.ALIASES
U_DSTM1          DSTM1(VCC=$G_DPWR GND=$G_DGND 1=OUT1 ) CN @DIGITAL SIGNAL
+SOURCE.SCHEMATIC1(sch_1):INS107@SOURCE.DigClock.Normal(chips)
U_DSTM2          DSTM2(VCC=$G_DPWR GND=$G_DGND 1=OUT2 ) CN @DIGITAL SIGNAL
+SOURCE.SCHEMATIC1(sch_1):INS145@SOURCE.DigClock.Normal(chips)
_    _(OUT1=OUT1)
_    _(OUT2=OUT2)
.ENDALIASES
