.ALIASES
V_V1            V1(+=PULSE1 -=0 ) CN @06.SCHEMATIC3(sch_1):INS38@SOURCE.VPULSE.Normal(chips)
V_V2            V2(+=PULSE2 -=0 ) CN @06.SCHEMATIC3(sch_1):INS223@SOURCE.VPULSE.Normal(chips)
_    _(PULSE1=PULSE1)
_    _(PULSE2=PULSE2)
.ENDALIASES
